// ─── AniList Tag 数据表（tag-data.js）────────────────────────────
// AniList 固定词库 tag（MediaTagCollection，共 425 个）→ 中文名 + 解释。
// 结构：{ [tag.name]: { zh: 中文名, descEn: 英文解释, descZh: 中文解释 } }
// 用法：const d = ANILIST_TAG_DATA[t.name]; const name = d?.zh || t.name;
// 维护：zh/descZh 由用户手动填写。词库为官方固定词库，几乎不变。
// ⚠ = 剧透 tag（isGeneralSpoiler），运行时过滤，可不用翻译。
window.ANILIST_TAG_DATA = {
  // ── Technical ──
  '4-koma': { zh: '四格漫画', descEn: 'A manga in the \'yonkoma\' format, which consists of four equal-sized panels arranged in a vertical strip.', descZh: '采用"四格漫画"（yonkoma）形式的漫画，由四个等大的格子垂直排列组成。' },
  'Achromatic': { zh: '黑白', descEn: 'Contains animation that is primarily done in black and white.', descZh: '包含主要以黑白绘制的动画。' },
  'Advertisement': { zh: '广告', descEn: 'Produced in order to promote the products of a certain company.', descZh: '为宣传某公司的产品而制作。' },
  'Anthology': { zh: '短篇集', descEn: 'A collection of separate works collated into a single release.', descZh: '将多个独立作品汇集为一部作品发行。' },
  'CGI': { zh: 'CG动画', descEn: 'Prominently features scenes created with computer-generated imagery.', descZh: '突出出现由电脑生成图像（CGI）制作的场景。' },
  'Episodic': { zh: '单元剧', descEn: 'Features story arcs that are loosely tied or lack an overarching plot.', descZh: '包含联系松散、缺乏整体主线的剧情单元。' },
  'Flash': { zh: 'Flash动画', descEn: 'Created using Flash animation techniques.', descZh: '使用 Flash 动画技术制作。' },
  'Full CGI': { zh: '全CG', descEn: 'Almost entirely created with computer-generated imagery.', descZh: '几乎全部由电脑生成图像（CGI）制作。' },
  'Full Color': { zh: '全彩', descEn: 'Manga that were initially published in full color.', descZh: '最初即以全彩出版的漫画。' },
  'Gekiga': { zh: '剧画', descEn: 'An alternative comics movement of mature manga with stylized and cinematic visuals predominantly from the late 1950s through 1970s.', descZh: '兴起于1950年代末至1970年代、以风格化与电影化画面著称的成人漫画另类运动。' },
  'Graduation Project': { zh: '毕业作品', descEn: 'A work made by students in place of an exam, typically at higher levels of education, either as a work for the entire course or as a work for a specific year of a course.', descZh: '由学生为代替考试而制作的作品，通常在高等教育阶段，可以是整个课程或某一年级的作品。' },
  'Long Strip': { zh: '长条漫画', descEn: 'Manga originally published in a vertical, long-strip format, designed for viewing on smartphones. Also known as webtoons.', descZh: '最初以竖长条形式出版、专为智能手机观看设计的漫画，也称 webtoon（条漫）。' },
  'Mixed Media': { zh: '混合媒体', descEn: 'Features a combination of different media and animation techniques. Often seen with puppetry, textiles, live action footage, stop motion, and more. This does not include works with normal usage of CGI in their production.', descZh: '包含多种媒体与动画技法的结合，常见于木偶戏、布料、实拍影像、定格动画等。不包含制作中正常使用CGI的作品。' },
  'No Dialogue': { zh: '无对白', descEn: 'This work contains no dialogue.', descZh: '作品不包含对白。' },
  'Non-fiction': { zh: '非虚构', descEn: 'A work that provides information regarding a real world topic and does not focus on an imaginary narrative.', descZh: '提供现实世界主题的信息、不以虚构叙事为主的作品。' },
  'POV': { zh: '第一人称视角', descEn: 'Point of View; features scenes shown from the perspective of the series protagonist.', descZh: '第一人称视角（Point of View）；包含从系列主角视角展现的场景。' },
  'Puppetry': { zh: '人偶剧', descEn: 'Animation style involving the manipulation of puppets to act out scenes.', descZh: '通过操纵人偶来演绎场景的动画风格。' },
  'Rotoscoping': { zh: '转描', descEn: 'Animation technique that animators use to trace over motion picture footage, frame by frame, to produce realistic action.', descZh: '动画师逐帧临摹实拍影像以产生写实动作的动画技法。' },
  'Short-Form Chapter': { zh: '极短章节', descEn: 'Manga which consists of the chapters being up to two pages long.', descZh: '每章最多两页的漫画。' },
  'Stop Motion': { zh: '定格动画', descEn: 'Animation style characterized by physical objects being moved incrementally between frames to create the illusion of movement.', descZh: '通过逐帧移动实物来营造运动错觉的动画风格。' },
  'Vertical Video': { zh: '竖屏视频', descEn: 'Animated works originally created in a vertical aspect ratio (such as 9:16), intended for viewing on smartphones.', descZh: '最初以竖屏比例（如9:16）制作、面向智能手机观看的动画作品。' },
  // ── Setting-Time ──
  'Achronological Order': { zh: '乱序叙事', descEn: 'Chapters or episodes do not occur in chronological order.', descZh: '章节或剧集不按时间顺序展开。' },
  'Anachronism': { zh: '时代错置', descEn: 'Prominently features elements that are out of place in the historical period the work takes place in, particularly modern elements in a historical setting.', descZh: '突出出现与作品所处历史时期不符的元素，尤其是历史背景下出现现代元素。' },
  'Ancient China': { zh: '古代中国', descEn: 'Setting in ancient china, does not apply to fantasy settings.', descZh: '设定在古代中国，不适用于奇幻设定。' },
  'Dystopian': { zh: '反乌托邦', descEn: 'Partly or completely set in a society characterized by poverty, squalor or oppression.', descZh: '部分或完全设定在充满贫穷、肮脏或压迫的社会中。' },
  'Historical': { zh: '历史', descEn: 'Partly or completely set during a real period of world history.', descZh: '部分或完全设定在世界历史的某个真实时期。' },
  'Medieval': { zh: '中世纪', descEn: 'Partially or completely set in the Middle Ages or a Middle Ages-inspired setting. Commonly features elements such as European castles and knights.', descZh: '部分或完全设定在中世纪或受中世纪启发的环境中，常见欧洲城堡与骑士等元素。' },
  'Time Skip': { zh: '时间跳跃', descEn: 'Features a gap in time used to advance the story.', descZh: '包含用于推进剧情的时间跳跃。' },
  // ── Theme-Game-Sport ──
  'Acrobatics': { zh: '杂技', descEn: 'The art of jumping, tumbling, and balancing. Often paired with trapeze, trampolining, tightropes, or general gymnastics.', descZh: '跳跃、翻滚与平衡的技巧，常与空中飞人、蹦床、走钢丝或一般体操结合。' },
  'Airsoft': { zh: '生存游戏', descEn: 'Centers around the sport of airsoft.', descZh: '围绕生存游戏（airsoft）运动展开。' },
  'American Football': { zh: '美式橄榄球', descEn: 'Centers around the sport of American football.', descZh: '围绕美式橄榄球运动展开。' },
  'Athletics': { zh: '田径', descEn: 'Centers around sporting events that involve competitive running, jumping, throwing, or walking.', descZh: '围绕赛跑、跳跃、投掷或竞走等竞技运动展开。' },
  'Badminton': { zh: '羽毛球', descEn: 'Centers around the sport of badminton.', descZh: '围绕羽毛球运动展开。' },
  'Baseball': { zh: '棒球', descEn: 'Centers around the sport of baseball.', descZh: '围绕棒球运动展开。' },
  'Basketball': { zh: '篮球', descEn: 'Centers around the sport of basketball.', descZh: '围绕篮球运动展开。' },
  'Bowling': { zh: '保龄球', descEn: 'Centers around the sport of Bowling.', descZh: '围绕保龄球运动展开。' },
  'Boxing': { zh: '拳击', descEn: 'Centers around the sport of boxing.', descZh: '围绕拳击运动展开。' },
  'Cheerleading': { zh: '啦啦队', descEn: 'Centers around the activity of cheerleading.', descZh: '围绕啦啦队活动展开。' },
  'Cycling': { zh: '骑行', descEn: 'Centers around the sport of cycling.', descZh: '围绕自行车运动展开。' },
  'Fencing': { zh: '击剑', descEn: 'Centers around the sport of fencing.', descZh: '围绕击剑运动展开。' },
  'Fishing': { zh: '钓鱼', descEn: 'Centers around the sport of fishing.', descZh: '围绕钓鱼运动展开。' },
  'Fitness': { zh: '健身', descEn: 'Centers around exercise with the aim of improving physical health.', descZh: '围绕以改善身体健康为目的的锻炼展开。' },
  'Football': { zh: '足球', descEn: 'Centers around the sport of football (known in the USA as "soccer").', descZh: '围绕足球运动展开（在美国称为 soccer）。' },
  'Golf': { zh: '高尔夫', descEn: 'Centers around the sport of golf.', descZh: '围绕高尔夫运动展开。' },
  'Handball': { zh: '手球', descEn: 'Centers around the sport of handball.', descZh: '围绕手球运动展开。' },
  'Ice Skating': { zh: '滑冰', descEn: 'Centers around the sport of ice skating.', descZh: '围绕滑冰运动展开。' },
  'Judo': { zh: '柔道', descEn: 'Centers around the sport of judo.', descZh: '围绕柔道运动展开。' },
  'Lacrosse': { zh: '长曲棍球', descEn: 'A team game played with a ball and lacrosse sticks.', descZh: '使用球与长曲棍球棍进行的团队运动。' },
  'Parkour': { zh: '跑酷', descEn: 'Centers around the sport of parkour.', descZh: '围绕跑酷运动展开。' },
  'Rugby': { zh: '橄榄球', descEn: 'Centers around the sport of rugby.', descZh: '围绕橄榄球运动展开。' },
  'Scuba Diving': { zh: '潜水', descEn: 'Prominently features characters diving with the aid of special breathing equipment.', descZh: '突出出现借助特殊呼吸设备潜水的角色。' },
  'Skateboarding': { zh: '滑板', descEn: 'Centers around or prominently features skateboarding as a sport.', descZh: '围绕或突出出现滑板运动。' },
  'Sumo': { zh: '相扑', descEn: 'Centers around the sport of sumo.', descZh: '围绕相扑运动展开。' },
  'Surfing': { zh: '冲浪', descEn: 'Centers around surfing as a sport.', descZh: '围绕冲浪运动展开。' },
  'Swimming': { zh: '游泳', descEn: 'Centers around the sport of swimming.', descZh: '围绕游泳运动展开。' },
  'Table Tennis': { zh: '乒乓球', descEn: 'Centers around the sport of table tennis (also known as "ping pong").', descZh: '围绕乒乓球运动展开（也称 ping pong）。' },
  'Tennis': { zh: '网球', descEn: 'Centers around the sport of tennis.', descZh: '围绕网球运动展开。' },
  'Volleyball': { zh: '排球', descEn: 'Centers around the sport of volleyball.', descZh: '围绕排球运动展开。' },
  'Wrestling': { zh: '摔跤', descEn: 'Centers around the sport of wrestling.', descZh: '围绕摔跤运动展开。' },
  // ── Theme-Arts ──
  'Acting': { zh: '表演', descEn: 'Centers around actors or the acting industry.', descZh: '围绕演员或演艺行业展开。' },
  'Ballet': { zh: '芭蕾', descEn: 'Prominently features the dance art of ballet. Both traditional and contemporary styles.', descZh: '突出出现芭蕾舞艺术，包含传统与现代风格。' },
  'Calligraphy': { zh: '书法', descEn: 'Centers around the art of calligraphy.', descZh: '围绕书法艺术展开。' },
  'Classic Literature': { zh: '古典文学', descEn: 'Discusses or adapts a work of classic world literature.', descZh: '讨论或改编一部世界古典文学作品。' },
  'Drawing': { zh: '绘画', descEn: 'Centers around the art of drawing, including manga and doujinshi.', descZh: '围绕绘画艺术展开，包括漫画与同人志。' },
  'Fashion': { zh: '时尚', descEn: 'Centers around the fashion industry.', descZh: '围绕时尚产业展开。' },
  'Food': { zh: '美食', descEn: 'Centers around cooking or food appraisal.', descZh: '围绕烹饪或美食鉴赏展开。' },
  'Kabuki': { zh: '歌舞伎', descEn: 'Prominently features the traditional Japanese theater art of kabuki.', descZh: '突出出现日本传统戏剧艺术歌舞伎。' },
  'Makeup': { zh: '化妆', descEn: 'Centers around the makeup industry.', descZh: '围绕化妆产业展开。' },
  'Manzai': { zh: '漫才', descEn: 'Prominently features an act of traditional Japanese comedy that involves two performers.', descZh: '突出出现由两人表演的日本传统喜剧形式漫才。' },
  'Modeling': { zh: '模特', descEn: 'Features a line of work with the purpose of displaying and advertising products such as makeup, clothing, and jewelry. Also includes posing artistically for figure drawing, painting, sculpting, and photography.', descZh: '包含以展示和宣传化妆品、服装、珠宝等产品为目的的职业，也包括为素描、绘画、雕塑和摄影摆造型。' },
  'Photography': { zh: '摄影', descEn: 'Centers around the use of cameras to capture photos.', descZh: '围绕使用相机拍摄照片展开。' },
  'Rakugo': { zh: '落语', descEn: 'Rakugo is the traditional Japanese performance art of comic storytelling.', descZh: '落语（rakugo）是日本传统的喜剧叙事表演艺术。' },
  'Writing': { zh: '写作', descEn: 'Centers around the profession of writing books or novels.', descZh: '围绕撰写书籍或小说的职业展开。' },
  // ── Theme-Other ──
  'Adoption': { zh: '收养', descEn: 'Features a character who has been adopted by someone who is neither of their biological parents.', descZh: '包含被非亲生父母收养的角色。' },
  'Animals': { zh: '动物', descEn: 'Prominently features animal characters in a leading role.', descZh: '突出出现担任主角的动物角色。' },
  'Astronomy': { zh: '天文', descEn: 'Relating or centered around the study of celestial objects and phenomena, space, or the universe.', descZh: '关于或围绕对天体、太空或宇宙的研究展开。' },
  'Autobiographical': { zh: '自传', descEn: 'Real stories and anecdotes written by the author about their own life.', descZh: '作者撰写的关于自己真实生活的故事与轶事。' },
  'Biographical': { zh: '传记', descEn: 'Based on true stories of real persons living or dead, written by another.', descZh: '基于在世或已故真人真事、由他人撰写的作品。' },
  'Blackmail': { zh: '勒索', descEn: 'Features a character blackmailing another.', descZh: '包含角色勒索他人。' },
  'Body Horror': { zh: '肉体恐怖', descEn: 'Features characters who undergo horrific transformations or disfigurement, often to their own detriment.', descZh: '包含角色经历恐怖变形或毁容，往往损害自身。' },
  'Body Image': { zh: '外貌焦虑', descEn: 'Features themes of self-esteem concerning perceived defects or flaws in appearance, such as body weight or disfigurement, and may discuss topics such as eating disorders, fatphobia, and body dysmorphia.', descZh: '包含有关外表缺陷或瑕疵（如体重或毁容）的自尊主题，可能涉及进食障碍、肥胖恐惧和身体畸形恐惧等话题。' },
  'Brainwashing': { zh: '洗脑', descEn: 'Centers on one or more characters who are mentally manipulated by others to behave abnormally or act against their own will.', descZh: '围绕一个或多个被他人精神操控、行为异常或违背自身意愿的角色展开。' },
  'Cannibalism': { zh: '同类相食', descEn: 'Prominently features the act of consuming another member of the same species as food.', descZh: '突出出现以同类为食的行为。' },
  'Chibi': { zh: 'SD', descEn: 'Features "super deformed" character designs with smaller, rounder proportions and a cute look.', descZh: '包含SD（super deformed，超变形）角色设计，身形更小更圆润，外观可爱。' },
  'Cosmic Horror': { zh: '宇宙恐怖', descEn: 'A type of horror that emphasizes human insignificance in the grand scope of cosmic reality; fearing the unknown and being powerless to fight it.', descZh: '一种强调人类在宏大宇宙现实中渺小无力的恐怖类型，即对未知的恐惧与无力反抗。' },
  'Creature Taming': { zh: '驯兽', descEn: 'Features the taming of animals, monsters, or other creatures.', descZh: '包含驯养动物、怪物或其他生物。' },
  'Crime': { zh: '犯罪', descEn: 'Centers around unlawful activities punishable by the state or other authority.', descZh: '围绕国家或其他权威机关可惩处的违法行为展开。' },
  'Crossover': { zh: '跨界联动', descEn: 'Centers around the placement of two or more otherwise discrete fictional characters, settings, or universes into the context of a single story.', descZh: '围绕将两个或多个原本独立的虚构角色、设定或世界观放入同一故事中展开。' },
  'Death Game': { zh: '死亡游戏', descEn: 'Features characters participating in a game, where failure results in death.', descZh: '包含参与失败即死亡的游戏的角色。' },
  'Denpa': { zh: '电波', descEn: 'Works that feature themes of social dissociation, delusions, and other issues like suicide, bullying, self-isolation, paranoia, and technological necessity in daily lives. Classic iconography: telephone poles, rooftops, and trains.', descZh: '包含社会疏离、妄想等主题的作品，常涉及自杀、霸凌、自我封闭、偏执以及日常中不可或缺的技术。经典意象：电线杆、屋顶与列车。' },
  'Drugs': { zh: '药物滥用', descEn: 'Prominently features the usage of drugs such as opioids, stimulants, hallucinogens etc.', descZh: '突出出现鸦片类药物、兴奋剂、致幻剂等药物的使用。' },
  'Economics': { zh: '经济', descEn: 'Centers around the field of economics.', descZh: '围绕经济学领域展开。' },
  'Educational': { zh: '教育', descEn: 'Primary aim is to educate the audience.', descZh: '主要目的是教育观众。' },
  'Environmental': { zh: '环保', descEn: 'Concern with the state of the natural world and how humans interact with it.', descZh: '关注自然世界的状况以及人类与自然的互动。' },
  'Ero Guro': { zh: '情色猎奇', descEn: 'Japanese literary and artistic movement originating in the 1930\'s. Works have a focus on grotesque eroticism, sexual corruption, and decadence.', descZh: '起源于1930年代的日本文学与艺术运动，作品聚焦怪诞色情、性堕落与颓废。' },
  'Filmmaking': { zh: '电影制作', descEn: 'Centers around the art of filmmaking.', descZh: '围绕电影制作艺术展开。' },
  'Found Family': { zh: '非血缘家人', descEn: 'Features a group of characters with no biological relations that are united in a group providing social support.', descZh: '包含一群没有血缘关系、组成提供社会支持的团体的角色。' },
  'Gambling': { zh: '赌博', descEn: 'Centers around the act of gambling.', descZh: '围绕赌博行为展开。' },
  'Gender Bending': { zh: '性转', descEn: 'Prominently features a character who dresses and behaves in a way characteristic of another gender, or has been transformed into a person of another gender.', descZh: '突出出现穿着和行为具有另一性别特征的角色，或已变成另一性别的角色。' },
  'Gore': { zh: '血腥', descEn: 'Prominently features graphic bloodshed and violence.', descZh: '突出出现血腥的流血与暴力场面。' },
  'Human Experimentation': { zh: '人体实验', descEn: 'Features experiments that use human and humanoid beings as test subjects.', descZh: '包含以人类及类人生物为实验对象的实验。' },
  'Indigenous Cultures': { zh: '原住民文化', descEn: 'Prominently features real-life indigenous cultures.', descZh: '突出出现现实中的原住民文化。' },
  'Language Barrier': { zh: '语言障碍', descEn: 'A barrier to communication between people who are unable to speak a common language.', descZh: '无法使用共同语言交流的人之间的沟通障碍。' },
  'LGBTQ+ Themes': { zh: 'LGBTQ+主题', descEn: 'Prominently features characters or themes associated with the LGBTQ+ community, such as sexuality or gender identity.', descZh: '突出出现与LGBTQ+群体相关的角色或主题，如性取向或性别认同。' },
  'Lost Civilization': { zh: '失落文明', descEn: 'Featuring a civilization with few ruins or records that exist in present day knowledge.', descZh: '包含在当今认知中遗留遗迹或记录甚少的文明。' },
  'Marriage': { zh: '婚姻', descEn: 'Centers around marriage between two or more characters.', descZh: '围绕两个或多个角色之间的婚姻展开。' },
  'Matriarchy': { zh: '母系社会', descEn: 'Prominently features a country that is ruled by a Queen or a society that is dominated by female inheritance.', descZh: '突出出现由女王统治的国家或以女性继承为主导的社会。' },
  'Medicine': { zh: '医学', descEn: 'Centered around the activities of people working in the field of medicine.', descZh: '围绕医学领域从业人员的活动展开。' },
  'Memory Manipulation': { zh: '记忆操控', descEn: 'Prominently features a character(s) who has had their memories altered.', descZh: '突出出现记忆被篡改的角色。' },
  'Meta': { zh: 'Meta', descEn: 'Features fourth wall-breaking references to itself or genre tropes.', descZh: '包含打破第四面墙、指涉自身或类型套路的元素。' },
  'Mountaineering': { zh: '登山', descEn: 'Prominently features characters discussing or hiking mountains.', descZh: '突出出现讨论或攀登高山的角色。' },
  'Noir': { zh: '黑色风格', descEn: 'Stylized as a cynical crime drama with low-key visuals.', descZh: '以冷峻视觉风格呈现的愤世嫉俗犯罪剧。' },
  'Otaku Culture': { zh: '御宅文化', descEn: 'Centers around the culture of a fanatical fan-base.', descZh: '围绕狂热粉丝群体的文化展开。' },
  'Pandemic': { zh: '瘟疫', descEn: 'Prominently features a disease prevalent over a whole country or the world.', descZh: '突出出现蔓延全国或全球的疾病。' },
  'Philosophy': { zh: '哲学', descEn: 'Relating or devoted to the study of the fundamental nature of knowledge, reality, and existence.', descZh: '关于或致力于研究知识、现实与存在的根本本质。' },
  'Politics': { zh: '政治', descEn: 'Centers around politics, politicians, or government activities.', descZh: '围绕政治、政客或政府活动展开。' },
  'Pregnancy': { zh: '怀孕', descEn: 'Features pregnant female characters or discusses the topic of pregnancy.', descZh: '包含怀孕的女性角色或讨论怀孕话题。' },
  'Prophecy': { zh: '预言', descEn: 'Features characters or plot elements that revolve around predicting the future.', descZh: '包含围绕预测未来展开的角色或剧情元素。' },
  'Proxy Battle': { zh: '代理战斗', descEn: 'A proxy battle is a battle where humans use creatures/robots to do the fighting for them, either by commanding those creatures/robots or by simply evolving them/changing them into battle mode.', descZh: '代理战斗指人类使用生物或机器人替自己作战，通过指挥它们或将其进化、切换为战斗模式。' },
  'Psychosexual': { zh: '性心理', descEn: 'Work that involves the psychological aspects of sexual impulses.', descZh: '涉及性冲动的心理层面的作品。' },
  'Reincarnation': { zh: '转生', descEn: 'Features a character being born again after death, typically as another person or in another world.', descZh: '包含死后重生（通常是另一个人或在另一个世界）的角色。' },
  'Religion': { zh: '宗教', descEn: 'Centers on the belief that humanity is related to supernatural, transcendental, and spiritual elements.', descZh: '围绕人类与超自然、超验和精神元素相关的信仰展开。' },
  'Rescue': { zh: '救援', descEn: 'Centers around operations that carry out urgent treatment of injuries, remove people from danger, or save lives. This includes series that are about search-and-rescue teams, trauma surgeons, firefighters, and more.', descZh: '围绕紧急救治伤员、将人脱离危险或拯救生命展开，包括搜救队、创伤外科医生、消防员等题材。' },
  'Royal Affairs': { zh: '王室政治', descEn: 'Features nobility, alliances, arranged marriage, succession disputes, religious orders and other elements of royal politics.', descZh: '包含贵族、联盟、包办婚姻、继承权争端、宗教团体等王室政治元素。' },
  'Slavery': { zh: '奴隶制', descEn: 'Prominently features slaves, slavery, or slave trade.', descZh: '突出出现奴隶、奴隶制度或奴隶贸易。' },
  'Software Development': { zh: '软件开发', descEn: 'Centers around characters developing or programming a piece of technology, software, gaming, etc.', descZh: '围绕角色开发或编写技术、软件、游戏等展开。' },
  'Survival': { zh: '生存', descEn: 'Centers around the struggle to live in spite of extreme obstacles.', descZh: '围绕在极端障碍下挣扎求生展开。' },
  'Terrorism': { zh: '恐怖主义', descEn: 'Centers around the activities of a terrorist or terrorist organization.', descZh: '围绕恐怖分子或恐怖组织的活动展开。' },
  'Torture': { zh: '酷刑', descEn: 'The act of deliberately inflicting severe pain or suffering upon another individual or oneself as a punishment or with a specific purpose.', descZh: '出于惩罚或特定目的，故意对他人或自己施加严重痛苦的行为。' },
  'Travel': { zh: '旅行', descEn: 'Centers around character(s) moving between places a significant distance apart.', descZh: '围绕角色在相距遥远的地点之间移动展开。' },
  'Vocal Synth': { zh: '电子歌姬', descEn: 'Features one or more singers or characters that are products of a synthesize singing program. Popular examples are Vocaloids, UTAUloids, and CeVIOs.', descZh: '包含一个或多个由合成歌声程序产生的歌手或角色，常见例子有Vocaloid、UTAUloid和CeVIO。' },
  'War': { zh: '战争', descEn: 'Partly or completely set during wartime.', descZh: '部分或完全设定在战争时期。' },
  // ── Setting-Universe ──
  'Afterlife': { zh: '死后世界', descEn: 'Partly or completely set in the afterlife.', descZh: '部分或完全设定在死后世界。' },
  'Alternate Universe': { zh: '平行宇宙', descEn: 'Features multiple alternate universes in the same series.', descZh: '同一系列中出现多个平行宇宙。' },
  'Augmented Reality': { zh: '增强现实', descEn: 'Prominently features events with augmented reality as the main setting.', descZh: '突出出现以增强现实为主要设定的情节。' },
  'Omegaverse': { zh: 'ABO世界观', descEn: 'Alternative universe that prominently features dynamics modeled after wolves in which there are alphas, betas, and omegas and heat cycles as well as impregnation, regardless of gender.', descZh: '以狼群社会为蓝本的平行世界观，包含 alpha、beta、omega 之分、发情期以及不分性别的受孕。' },
  'Post-Apocalyptic': { zh: '后末日', descEn: 'Partly or completely set in a world or civilization after a global disaster.', descZh: '部分或完全设定在全球灾难之后的世界或文明中。' },
  'Space': { zh: '太空', descEn: 'Partly or completely set in outer space.', descZh: '部分或完全设定在外太空。' },
  'Urban Fantasy': { zh: '都市奇幻', descEn: 'Set in a world similar to the real world, but with the existence of magic or other supernatural elements.', descZh: '设定在与现实世界相似、但存在魔法或其他超自然元素的世界。' },
  'Virtual World': { zh: '虚拟世界', descEn: 'Partly or completely set in the world inside a video game.', descZh: '部分或完全设定在电子游戏的世界中。' },
  // ── Theme-Romance ──
  'Age Gap': { zh: '年龄差', descEn: 'Prominently features romantic relations between people with a significant age difference.', descZh: '突出出现年龄差距悬殊的人物之间的恋爱关系。' },
  'Boys\' Love': { zh: 'BL', descEn: 'Prominently features romance between two males, not inherently sexual.', descZh: '突出描写两名男性之间的恋爱，并非必然涉及性。' },
  'Cheating': { zh: '出轨', descEn: 'Features a character with a partner shown being intimate with someone else consensually.', descZh: '包含有伴侣的角色与他人自愿发生亲密关系。' },
  'Cohabitation': { zh: '同居', descEn: 'Features two or more people who live in the same household and develop a romantic or sexual relationship.', descZh: '包含同住一屋檐下并发展出恋爱或性关系的两人或多人。' },
  'Female Harem': { zh: '后宫', descEn: 'Main cast features the protagonist plus several female characters who are romantically interested in them.', descZh: '主角加上多位对他有好感的女性角色构成主要阵容。' },
  'Heterosexual': { zh: '异性恋', descEn: 'Prominently features a romance between a man and a woman, not inherently sexual.', descZh: '突出描写男性和女性之间的恋爱，并非必然涉及性。' },
  'Incest': { zh: '近亲恋爱', descEn: 'Features sexual or romantic relations between characters who are related by blood.', descZh: '包含有血缘关系的角色之间的性爱或恋爱关系。' },
  'Inseki': { zh: '非血缘家人恋爱', descEn: 'Features sexual or romantic relations among step, adopted, and other non-blood related family members.', descZh: '包含继亲、收养等无血缘关系家庭成员之间的性爱或恋爱关系。' },
  'Interspecies': { zh: '跨种族恋爱', descEn: 'Romance between characters of different species.', descZh: '不同种族角色之间的恋爱。' },
  'Love Triangle': { zh: '三角恋', descEn: 'Centered around romantic feelings between more than two people. Includes all love polygons.', descZh: '围绕两人以上的恋爱感情展开，包括所有多角恋。' },
  'Male Harem': { zh: '逆后宫', descEn: 'Main cast features the protagonist plus several male characters who are romantically interested in them.', descZh: '主角加上多位对他有好感的男性角色构成主要阵容。' },
  'Matchmaking': { zh: '相亲', descEn: 'Prominently features either a matchmaker or events with the intent of matchmaking with eventual marriage in sight.', descZh: '突出出现媒人或以促成婚姻为目的的相亲活动。' },
  'Mixed Gender Harem': { zh: '混合后宫', descEn: 'Main cast features the protagonist plus several people, regardless of gender, who are romantically interested in them.', descZh: '主角加上多位（不论性别）对他有好感的人构成主要阵容。' },
  'Polyamorous': { zh: '多角恋', descEn: 'Features a character who is in a consenting relationship with multiple people at one time.', descZh: '包含同时与多人保持自愿关系的角色。' },
  'Teens\' Love': { zh: '少女向恋爱', descEn: 'Sexually explicit love-story between individuals of the opposite sex, specifically targeting females of teens and young adult age.', descZh: '异性之间包含露骨性描写的恋爱故事，目标为少女及年轻女性。' },
  'Unrequited Love': { zh: '单恋', descEn: 'One or more characters are experiencing an unrequited love that may or may not be reciprocated.', descZh: '一个或多个角色经历的单恋，可能得到回应也可能没有。' },
  'Yuri': { zh: '百合', descEn: 'Prominently features romance between two females, not inherently sexual. Also known as Girls\' Love.', descZh: '突出描写两名女性之间的恋爱，并非必然涉及性，也称百合（Girls\' Love）。' },
  // ── Cast-Traits ──
  'Age Regression': { zh: '返老还童', descEn: 'Prominently features a character who was returned to a younger state.', descZh: '突出出现被变回年轻状态的角色。' },
  'Agender': { zh: '无性别', descEn: 'Prominently features agender characters.', descZh: '突出出现无性别角色。' },
  'Aliens': { zh: '外星人', descEn: 'Prominently features extraterrestrial lifeforms.', descZh: '突出出现外星生命体。' },
  'Amnesia': { zh: '失忆', descEn: 'Prominently features a character(s) with memory loss.', descZh: '突出出现失忆的角色。' },
  'Angels': { zh: '天使', descEn: 'Prominently features spiritual beings usually represented with wings and halos and believed to be attendants of God.', descZh: '突出出现通常以翅膀和光环为代表、被视为上帝侍者的灵性存在。' },
  'Anthropomorphism': { zh: '拟人化', descEn: 'Contains non-human character(s) that have attributes or characteristics of a human being.', descZh: '包含具有人类属性或特征的非人角色。' },
  'Aromantic': { zh: '无浪漫取向', descEn: 'Features a character who experiences little to no romantic attraction.', descZh: '包含几乎或完全不产生浪漫吸引的角色。' },
  'Arranged Marriage': { zh: '包办婚姻', descEn: 'Features two characters made to marry each other, usually by their family.', descZh: '包含两个被（通常是家人）安排结婚的角色。' },
  'Artificial Intelligence': { zh: '人工智能', descEn: 'Intelligent non-organic machines that work and react similarly to humans.', descZh: '能够像人类一样工作与反应的智能非有机机器。' },
  'Asexual': { zh: '无性取向', descEn: 'Features a character who isn\'t sexually attracted to people of any sex or gender.', descZh: '包含对任何性别的人都不产生性吸引的角色。' },
  'Bisexual': { zh: '双性恋', descEn: 'Features a character who is romantically or sexually attracted to people of more than one sex or gender.', descZh: '包含对不止一种性别产生浪漫或性吸引的角色。' },
  'Butler': { zh: '管家', descEn: 'Prominently features a character who is a butler.', descZh: '突出出现管家角色。' },
  'Centaur': { zh: '半人马', descEn: 'Prominently features a character with a human upper body and the lower body of a horse.', descZh: '突出出现上身为人、下身为马的半人马角色。' },
  'Chimera': { zh: '合成兽', descEn: 'Features a beast made by combining animals, usually with humans.', descZh: '包含由动物（通常结合人类）组合而成的合成兽。' },
  'Chuunibyou': { zh: '中二病', descEn: 'Prominently features a character with "Middle School 2nd Year Syndrome", who either acts like a know-it-all adult or falsely believes they have special powers.', descZh: '突出出现患有"中二病"（chuunibyou，初中二年级症候群）的角色——要么装成无所不知的大人，要么妄信自己有超能力。' },
  'Clone': { zh: '克隆人', descEn: 'Prominently features a character who is an artificial exact copy of another organism.', descZh: '突出出现作为其他生物人工精确复制品的角色。' },
  'Cosplay': { zh: '角色扮演', descEn: 'Features dressing up as a different character or profession.', descZh: '包含打扮成其他角色或职业。' },
  'Cowboys': { zh: '牛仔', descEn: 'Features Western or Western-inspired cowboys.', descZh: '包含西部或受西部启发的牛仔。' },
  'Crossdressing': { zh: '异装', descEn: 'Prominently features a character dressing up as the opposite sex.', descZh: '突出出现打扮成异性的角色。' },
  'Cyborg': { zh: '改造人', descEn: 'Prominently features a human character whose physiological functions are aided or enhanced by artificial means.', descZh: '突出出现生理机能由人工手段辅助或强化的改造人角色。' },
  'Delinquents': { zh: '不良', descEn: 'Features characters with a notorious image and attitude, sometimes referred to as "yankees".', descZh: '包含形象与态度恶劣、有时被称为"yankee"的不良少年角色。' },
  'Demons': { zh: '恶魔', descEn: 'Prominently features malevolent otherworldly creatures.', descZh: '突出出现邪恶的超自然生物。' },
  'Detective': { zh: '侦探', descEn: 'Features a character who investigates and solves crimes.', descZh: '包含调查并破案的角色。' },
  'Dinosaurs': { zh: '恐龙', descEn: 'Prominently features Dinosaurs, prehistoric reptiles that went extinct millions of years ago.', descZh: '突出出现数百万年前灭绝的史前爬行动物恐龙。' },
  'Disability': { zh: '残障', descEn: 'A work that features one or more characters with a physical, mental, cognitive, or developmental condition that impairs, interferes with, or limits the person\'s ability to engage in certain tasks or actions.', descZh: '包含一个或多个患有身体、精神、认知或发育障碍、从而损害或限制其从事某些活动能力的角色的作品。' },
  'Dissociative Identities': { zh: '多重人格', descEn: 'A case where one or more people share the same body.', descZh: '多人共用一个身体的情况。' },
  'Dragons': { zh: '龙', descEn: 'Prominently features mythical reptiles which generally have wings and can breathe fire.', descZh: '突出出现通常有翅膀且会喷火的神话爬行动物。' },
  'Dullahan': { zh: '无头骑士', descEn: 'Prominently features a character who is a Dullahan, a creature from Irish Folklore with a head that can be detached from its main body.', descZh: '突出出现爱尔兰民间传说中头可与身体分离的无头骑士角色。' },
  'Elf': { zh: '精灵', descEn: 'Prominently features a character who is an elf.', descZh: '突出出现精灵角色。' },
  'Fairy': { zh: '妖精', descEn: 'Prominently features a character who is a fairy.', descZh: '突出出现妖精角色。' },
  'Femboy': { zh: '伪娘', descEn: 'Features a boy who exhibits characteristics or behaviors considered in many cultures to be typical of girls.', descZh: '包含表现出在许多文化中被视为女孩典型特征或行为的男孩。' },
  'Ghost': { zh: '幽灵', descEn: 'Prominently features a character who is a ghost.', descZh: '突出出现幽灵角色。' },
  'Goblin': { zh: '哥布林', descEn: 'A goblin is a monstrous creature from European folklore. They are almost always small and grotesque, mischievous or outright malicious, and greedy. Sometimes with magical abilities.', descZh: '哥布林（goblin）是源自欧洲民间传说的怪物，几乎总是体型矮小丑陋、爱恶作剧或完全恶毒、贪婪，有时具有魔法能力。' },
  'Gods': { zh: '神明', descEn: 'Prominently features a character of divine or religious nature.', descZh: '突出出现具有神圣或宗教性质的角色。' },
  'Gyaru': { zh: '辣妹', descEn: 'Prominently features a female character who has a distinct American-emulated fashion style, such as tanned skin, bleached hair, and excessive makeup. Also known as gal.', descZh: '突出出现具有明显模仿美式风格（如晒黑皮肤、漂白头发、浓妆）的女性角色，也称辣妹（gal）。' },
  'Hikikomori': { zh: '家里蹲', descEn: 'Prominently features a character who withdraws from social life, often seeking extreme isolation.', descZh: '突出出现脱离社会生活、常寻求极端封闭的角色。' },
  'Homeless': { zh: '无家可归', descEn: 'Prominently features a character that is homeless.', descZh: '突出出现无家可归的角色。' },
  'Idol': { zh: '偶像', descEn: 'Centers around the life and activities of an idol.', descZh: '围绕偶像的生活与活动展开。' },
  'Kemonomimi': { zh: '兽耳', descEn: 'Prominently features humanoid characters with animal ears.', descZh: '突出出现带有动物耳朵的类人角色。' },
  'Kuudere': { zh: '冷娇', descEn: 'Prominently features a character who generally retains a cold, blunt and cynical exterior, but once one gets to know them, they have a very warm and loving interior.', descZh: '突出出现外表冷静、直率、愤世嫉俗，但熟悉后会展现出温暖爱意的角色。' },
  'Maids': { zh: '女仆', descEn: 'Prominently features a character who is a maid.', descZh: '突出出现女仆角色。' },
  'Mermaid': { zh: '人鱼', descEn: 'A mythological creature with the body of a human and the tail of a fish.', descZh: '拥有人类身体与鱼尾的神话生物。' },
  'Monster Boy': { zh: '人外男', descEn: 'Prominently features a male character who is a part-monster.', descZh: '突出出现半怪物的男性角色。' },
  'Monster Girl': { zh: '人外娘', descEn: 'Prominently features a female character who is part-monster.', descZh: '突出出现半怪物的女性角色。' },
  'Nekomimi': { zh: '猫耳', descEn: 'Humanoid characters with cat-like features such as cat ears and a tail.', descZh: '具有猫耳、尾巴等猫类特征的类人角色。' },
  'Ninja': { zh: '忍者', descEn: 'Prominently features Japanese warriors traditionally trained in espionage, sabotage and assasination.', descZh: '突出出现传统上接受间谍、破坏与暗杀训练的日本武士。' },
  'Nudity': { zh: '裸体', descEn: 'Features a character wearing no clothing or exposing intimate body parts.', descZh: '包含不穿衣物或暴露私密部位的角色。' },
  'Nun': { zh: '修女', descEn: 'Prominently features a character who is a nun.', descZh: '突出出现修女角色。' },
  'Office Lady': { zh: 'OL', descEn: 'Prominently features a female office worker or OL.', descZh: '突出出现女性上班族或OL（office lady）。' },
  'Oiran': { zh: '花魁', descEn: 'Prominently features a courtesan character of the Japanese Edo Period.', descZh: '突出出现日本江户时代的花魁（高级游女）角色。' },
  'Ojou-sama': { zh: '大小姐', descEn: 'Features a wealthy, high-class, oftentimes stuck up and demanding female character.', descZh: '包含富裕、上流、往往傲慢任性的千金小姐角色。' },
  'Orphan': { zh: '孤儿', descEn: 'Prominently features a character that is an orphan.', descZh: '突出出现孤儿角色。' },
  'Pirates': { zh: '海盗', descEn: 'Prominently features sea-faring adventurers branded as criminals by the law.', descZh: '突出出现被法律视为罪犯的航海冒险者。' },
  'Robots': { zh: '机器人', descEn: 'Prominently features humanoid machines.', descZh: '突出出现人形机器。' },
  'Samurai': { zh: '武士', descEn: 'Prominently features warriors of medieval Japanese nobility bound by a code of honor.', descZh: '突出出现受荣誉准则约束的日本中世纪贵族武士。' },
  'Shrine Maiden': { zh: '巫女', descEn: 'Prominently features a character who is a shrine maiden.', descZh: '突出出现巫女角色。' },
  'Skeleton': { zh: '骷髅', descEn: 'Prominently features skeleton(s) as a character.', descZh: '突出出现骷髅角色。' },
  'Succubus': { zh: '魅魔', descEn: 'Prominently features a character who is a succubus, a creature in medieval folklore that typically uses their sexual prowess to trap and seduce people to feed off them.', descZh: '突出出现魅魔（succubus）角色——中世纪民间传说中通常利用性魅力引诱人并吸取其精气的生物。' },
  'Tanned Skin': { zh: '晒黑皮肤', descEn: 'Prominently features characters with tanned skin.', descZh: '突出出现晒黑皮肤的角色。' },
  'Teacher': { zh: '教师', descEn: 'Protagonist is an educator, usually in a school setting.', descZh: '主角是教育者，通常在校园环境中。' },
  'Tomboy': { zh: '假小子', descEn: 'Features a girl who exhibits characteristics or behaviors considered in many cultures to be typical of boys.', descZh: '包含表现出在许多文化中被视为男孩典型特征或行为的女孩。' },
  'Transgender': { zh: '跨性别', descEn: 'Features a character whose gender identity differs from the sex they were assigned at birth.', descZh: '包含性别认同与出生时指定性别不同的角色。' },
  'Tsundere': { zh: '傲娇', descEn: 'Prominently features a character who acts cold and hostile in order to mask warmer emotions.', descZh: '突出出现用冷淡敌意掩饰内心温暖情感的角色。' },
  'Twins': { zh: '双胞胎', descEn: 'Prominently features two or more siblings that were born at one birth.', descZh: '突出出现一次出生两个或更多兄弟姐妹。' },
  'Vampire': { zh: '吸血鬼', descEn: 'Prominently features a character who is a vampire.', descZh: '突出出现吸血鬼角色。' },
  'Veterinarian': { zh: '兽医', descEn: 'Prominently features a veterinarian or one of the main characters is a veterinarian.', descZh: '突出出现兽医，或主角之一是兽医。' },
  'Vikings': { zh: '维京人', descEn: 'Prominently features Scandinavian seafaring pirates and warriors.', descZh: '突出出现斯堪的纳维亚的航海海盗与战士。' },
  'Villainess': { zh: '恶役千金', descEn: 'Centers around or prominently features a villainous noble lady.', descZh: '围绕或突出出现恶役千金（反派贵族小姐）。' },
  'VTuber': { zh: '虚拟主播', descEn: 'Prominently features a character who is either an actual or fictive VTuber.', descZh: '突出出现真实或虚构的虚拟主播（VTuber）角色。' },
  'Werewolf': { zh: '狼人', descEn: 'Prominently features a character who is a werewolf.', descZh: '突出出现狼人角色。' },
  'Witch': { zh: '魔女', descEn: 'Prominently features a character who is a witch.', descZh: '突出出现魔女角色。' },
  'Yandere': { zh: '病娇', descEn: 'Prominently features a character who is obsessively in love with another, to the point of acting deranged or violent.', descZh: '突出出现对他人爱到痴迷、甚至行为失常或暴力的角色。' },
  'Zombie': { zh: '僵尸', descEn: 'Prominently features reanimated corpses which often prey on live humans and turn them into zombies.', descZh: '突出出现复活的尸体，通常捕食活人并将其变成僵尸。' },
  // ── Theme-Slice of Life ──
  'Agriculture': { zh: '农业', descEn: 'Prominently features agriculture practices.', descZh: '突出出现农业活动。' },
  'Cute Boys Doing Cute Things': { zh: '男子轻日常', descEn: 'Centers around male characters doing cute activities, usually with little to no emphasis on drama and conflict.', descZh: '围绕男性角色做可爱的事情展开，通常几乎不强调戏剧与冲突。' },
  'Cute Girls Doing Cute Things': { zh: '萌系日常', descEn: 'Centers around female characters doing cute activities, usually with little to no emphasis on drama and conflict.', descZh: '围绕女性角色做可爱的事情展开，通常几乎不强调戏剧与冲突。' },
  'Family Life': { zh: '家庭生活', descEn: 'Centers around the activities of a family unit.', descZh: '围绕家庭成员的活动展开。' },
  'Horticulture': { zh: '园艺', descEn: 'The story prominently features plant care and gardening.', descZh: '故事突出出现植物养护与园艺。' },
  'Iyashikei': { zh: '治愈系', descEn: 'Primary aim is to heal the audience through serene depictions of characters\' daily lives.', descZh: '主要目的是通过宁静描绘角色的日常生活来治愈观众。' },
  'Parenthood': { zh: '育儿', descEn: 'Centers around the experience of raising a child.', descZh: '围绕养育孩子的经历展开。' },
  // ── Sexual Content ──
  'Ahegao': { zh: '阿黑颜', descEn: 'Features a character making an exaggerated orgasm face.', descZh: '包含做出夸张高潮表情（ahegao）的角色。' },
  'Amputation': { zh: '截肢', descEn: 'Features amputation or amputees.', descZh: '包含截肢或截肢者。' },
  'Anal Sex': { zh: '肛交', descEn: 'Features sexual penetration of the anal cavity.', descZh: '包含对肛门的性插入。' },
  'Armpits': { zh: '腋下', descEn: 'Features the sexual depiction or stimulation of a character\'s armpits.', descZh: '包含对角色腋下的性描写或刺激。' },
  'Ashikoki': { zh: '足交', descEn: 'Footjob; features stimulation of genitalia by feet.', descZh: '足交（footjob）；包含用脚刺激生殖器。' },
  'Asphyxiation': { zh: '窒息', descEn: 'Features breath play.', descZh: '包含呼吸控制（breath play）。' },
  'Bondage': { zh: '束缚', descEn: 'Features BDSM, with or without the use of accessories.', descZh: '包含BDSM（束缚调教），无论是否使用辅助道具。' },
  'Boobjob': { zh: '乳交', descEn: 'Features the stimulation of male genitalia by breasts.', descZh: '包含用胸部刺激男性生殖器。' },
  'Cervix Penetration': { zh: '宫颈插入', descEn: 'A sexual act in which the cervix is visibly penetrated.', descZh: '一种可见插入子宫颈的性行为。' },
  'Cumflation': { zh: '精液膨胀', descEn: 'The stomach area expands outward like a balloon due to being filled specifically with semen.', descZh: '腹部因充满精液而像气球一样向外膨胀。' },
  'Cunnilingus': { zh: '口交（女）', descEn: 'Features oral sex performed on female genitalia.', descZh: '包含对女性生殖器进行的口交。' },
  'Deepthroat': { zh: '深喉', descEn: 'Features oral sex where the majority of the erect male genitalia is inside another person\'s mouth, usually stimulating some gagging in the back of their throat.', descZh: '包含大部分勃起男性生殖器进入对方口中的口交，通常会引起喉咙深处的干呕反应。' },
  'Defloration': { zh: '初体验', descEn: 'Features a female character who has never had sexual relations (until now).', descZh: '包含从未有过性经历（直到现在）的女性角色。' },
  'DILF': { zh: 'DILF', descEn: 'Features sexual intercourse with older men.', descZh: '包含与年长男性的性交。' },
  'Double Penetration': { zh: '双重插入', descEn: 'A sexual act in which the vagina/anus are penetrated by two penises/toys.', descZh: '阴道或肛门同时被两个阴茎或玩具插入的性行为。' },
  'Erotic Piercings': { zh: '情色穿刺', descEn: 'Features a type of body modification designed to enhance sexual pleasure and intimacy, and/or decoratively adorns portions of the body considered sexual in nature.', descZh: '包含旨在增强性快感与亲密感、或装饰被认为具有性意味部位的穿刺（body modification）。' },
  'Exhibitionism': { zh: '露出', descEn: 'Features the act of exposing oneself in public for sexual pleasure.', descZh: '包含为获得性快感而在公共场合暴露自己。' },
  'Facial': { zh: '颜射', descEn: 'Features sexual ejaculation onto an individual\'s face.', descZh: '包含将精液射在他人脸上。' },
  'Feet': { zh: '足', descEn: 'Features the sexual depiction or stimulation of a character\'s feet.', descZh: '包含对角色足部的性描写或刺激。' },
  'Fellatio': { zh: '口交（男）', descEn: 'Blowjob; features oral sex performed on male genitalia.', descZh: '口交（blowjob）；包含对男性生殖器进行的口交。' },
  'Femdom': { zh: '女性支配', descEn: 'Female Dominance. Features sexual acts with a woman in a dominant position.', descZh: '女性支配（Female Dominance）；包含女性处于支配地位的性行为。' },
  'Fingering': { zh: '指交', descEn: 'Features vaginal or anal insertion of fingers.', descZh: '包含手指插入阴道或肛门。' },
  'Fisting': { zh: '拳交', descEn: 'A sexual activity that involves inserting one or more hands into the vagina or rectum.', descZh: '将一只手或多只手插入阴道或直肠的性行为。' },
  'Flat Chest': { zh: '贫乳', descEn: 'Features a female character with smaller-than-average breasts.', descZh: '包含胸部小于平均的女性角色。' },
  'Futanari': { zh: '扶她', descEn: 'Features female characters with male genitalia.', descZh: '包含同时具有男性生殖器的女性角色。' },
  'Group Sex': { zh: '群交', descEn: 'Features more than two participants engaged in sex simultaneously.', descZh: '包含两人以上同时进行性行为。' },
  'Hair Pulling': { zh: '扯发', descEn: 'A sexual act in which the giver will grab the receivers hair and tug whilst giving pleasure from behind.', descZh: '一种性行为，施与者从背后给予快感时抓住受者的头发拉扯。' },
  'Handjob': { zh: '手交', descEn: 'Features the stimulation of genitalia by another\'s hands.', descZh: '包含用手刺激他人的生殖器。' },
  'Human Pet': { zh: '人宠', descEn: 'Features characters in a master-slave relationship where one is the "owner" and the other is a "pet."', descZh: '包含主仆关系的角色，一方是"主人"，另一方是"宠物"。' },
  'Hypersexuality': { zh: '性欲过盛', descEn: 'Portrays a character with a hypersexuality disorder, compulsive sexual behavior, or sex addiction.', descZh: '描绘患有性欲亢进障碍、强迫性性行为或性成瘾的角色。' },
  'Irrumatio': { zh: '口交（插入式）', descEn: 'Oral rape; features a character thrusting their genitalia or a phallic object into the mouth of another character.', descZh: '口交强奸（oral rape）；包含角色将生殖器或假阳具插入他人口中。' },
  'Lactation': { zh: '哺乳', descEn: 'Features breast milk play and production.', descZh: '包含泌乳与乳汁玩法。' },
  'Large Breasts': { zh: '巨乳', descEn: 'Features a character with larger-than-average breasts.', descZh: '包含胸部大于平均的角色。' },
  'Male Pregnancy': { zh: '男性怀孕', descEn: 'Features pregnant male characters in a sexual context.', descZh: '在性语境下包含怀孕的男性角色。' },
  'Masochism': { zh: '受虐', descEn: 'Prominently features characters who get sexual pleasure from being hurt or controlled by others.', descZh: '突出出现从被他人伤害或控制中获得性快感的角色。' },
  'Masturbation': { zh: '自慰', descEn: 'Features erotic stimulation of one\'s own genitalia or other erogenous regions.', descZh: '包含对自己生殖器或其他性感带的性刺激。' },
  'Mating Press': { zh: '压腿式', descEn: 'Features the sex position in which two partners face each other, with one of them thrusting downwards and the other\'s legs tucked up towards their head.', descZh: '一种性爱姿势，双方面对面，一方向下冲刺，另一方双腿蜷向头部。' },
  'MILF': { zh: '熟女', descEn: 'Features sexual intercourse with older women.', descZh: '包含与年长女性的性交。' },
  'Nakadashi': { zh: '中出', descEn: 'Creampie; features sexual ejaculation inside of a character.', descZh: '中出（creampie）；包含将精液射入角色体内。' },
  'Netorare': { zh: 'NTR', descEn: 'Netorare is what happens when the protagonist gets their partner stolen from them by someone else. It is a sexual fetish designed to cause sexual jealousy by way of having the partner indulge in sexual activity with someone other than the protagonist.', descZh: '寝取（netorare，NTR）指主角的伴侣被别人夺走，是通过伴侣与他人发生性关系来引发性嫉妒的性癖。' },
  'Netorase': { zh: 'NTRS', descEn: 'Features characters in a romantic relationship who agree to be sexually intimate with others.', descZh: '包含恋爱关系中的双方同意与他人发生性行为。' },
  'Netori': { zh: 'NTL', descEn: 'Features the protagonist stealing the partner of someone else. The opposite of netorare.', descZh: '包含主角夺走别人的伴侣，与寝取（netorare）相反。' },
  'Oyakodon': { zh: '亲子丼', descEn: 'Features a character who has sexual relations with both the mother and her daughter.', descZh: '包含与母亲和女儿双方发生性关系的角色（母女丼）。' },
  'Pet Play': { zh: '宠物Play', descEn: 'Treating a participant as though they were a pet animal. Often involves a collar and possibly BDSM.', descZh: '将参与者当作宠物动物对待，常涉及项圈并可能包含BDSM。' },
  'Prostitution': { zh: '卖淫', descEn: 'Features characters who are paid for sexual favors.', descZh: '包含以性服务换取报酬的角色。' },
  'Public Sex': { zh: '公共场合性行为', descEn: 'Features sexual acts performed in public settings.', descZh: '包含在公共场合进行的性行为。' },
  'Rape': { zh: '强奸', descEn: 'Features non-consensual sexual penetration.', descZh: '包含未经同意的性插入。' },
  'Rimjob': { zh: '舔肛', descEn: 'Features oral sex performed on the anus.', descZh: '包含对肛门进行的口交。' },
  'Sadism': { zh: '施虐', descEn: 'Prominently features characters deriving pleasure, especially sexual gratification, from inflicting pain, suffering, or humiliation on others.', descZh: '突出出现从对他人施加痛苦、折磨或羞辱中获得快感（尤其是性快感）的角色。' },
  'Scat': { zh: '排泄', descEn: 'Lots of feces.', descZh: '包含大量排泄物（scat）。' },
  'Scissoring': { zh: '剪刀式', descEn: 'A form of sexual activity between women in which the genitals are stimulated by being rubbed against one another.', descZh: '女性之间通过生殖器相互摩擦刺激的性行为。' },
  'Sex Toys': { zh: '情趣玩具', descEn: 'Features objects that are designed to stimulate sexual pleasure.', descZh: '包含旨在刺激性快感的情趣玩具。' },
  'Shimaidon': { zh: '姐妹丼', descEn: 'Features a character who has sexual relations with two sisters.', descZh: '包含与姐妹两人发生性关系的角色（姐妹丼）。' },
  'Sixty-nine': { zh: '69式', descEn: 'Features two characters partaking in oral sex simultaneously.', descZh: '包含两人同时进行口交。' },
  'Squirting': { zh: '潮吹', descEn: 'Female ejaculation; features the expulsion of liquid from the female genitalia.', descZh: '女性射液（female ejaculation）；包含从女性生殖器排出液体。' },
  'Sumata': { zh: '素股', descEn: 'Pussyjob; features the stimulation of male genitalia by the thighs and labia majora of a female character.', descZh: '素股（pussyjob）；包含女性用大腿与阴唇刺激男性生殖器。' },
  'Swapping': { zh: '交换伴侣', descEn: 'Features consensual partner swapping between couples during sexual activities.', descZh: '包含伴侣之间自愿交换性伴侣。' },
  'Sweat': { zh: '汗', descEn: 'Lots of sweat.', descZh: '包含大量汗水。' },
  'Tentacles': { zh: '触手', descEn: 'Features the long appendages most commonly associated with octopuses or squid, often sexually penetrating a character.', descZh: '包含最常见于章鱼或鱿鱼的长触手，常插入角色体内。' },
  'Threesome': { zh: '3P', descEn: 'Features sexual acts between three people.', descZh: '包含三人之间的性行为。' },
  'Virginity': { zh: '童贞', descEn: 'Features a male character who has never had sexual relations (until now).', descZh: '包含从未有过性经历（直到现在）的男性角色。' },
  'Vore': { zh: '吞食', descEn: 'Features a character being swallowed or swallowing another creature whole.', descZh: '包含角色被整个吞下或整个吞下另一个生物。' },
  'Voyeur': { zh: '偷窥', descEn: 'Features a character who enjoys seeing the sex acts or sex organs of others.', descZh: '包含喜欢观看他人性行为或性器官的角色。' },
  'Watersports': { zh: '放尿', descEn: 'Features sexual situations involving urine.', descZh: '包含涉及尿液的性场景。' },
  'Zoophilia': { zh: '兽交', descEn: 'Features a character who has a sexual attraction for non-human animals.', descZh: '包含对非人类动物产生性吸引的角色。' },
  // ── Theme-Fantasy ──
  'Alchemy': { zh: '炼金术', descEn: 'Features character(s) who practice alchemy.', descZh: '包含修炼炼金术的角色。' },
  'Body Swapping': { zh: '身体互换', descEn: 'Centers around individuals swapping bodies with one another.', descZh: '围绕角色之间互换身体展开。' },
  'Cultivation': { zh: '修仙', descEn: 'Features characters using training, often martial arts-related, and other special methods to cultivate qi (a component of traditional Chinese philosophy, described as "life force") and gain strength or immortality.', descZh: '包含角色通过修炼（常与武术相关）及其他特殊方法培育气（中国传统哲学中称为"生命之力"的组成部分）以获得力量或长生。' },
  'Curses': { zh: '诅咒', descEn: 'Features a character, object or area that has been cursed, usually by a malevolent supernatural force.', descZh: '包含被（通常是恶意的超自然力量）诅咒的角色、物体或区域。' },
  'Exorcism': { zh: '驱魔', descEn: 'Involving religious methods of vanquishing youkai, demons, or other supernatural entities.', descZh: '涉及用宗教方法消灭妖怪、恶魔或其他超自然实体。' },
  'Fairy Tale': { zh: '童话', descEn: 'This work tells a fairy tale, centers around fairy tales, or is based on a classic fairy tale.', descZh: '讲述童话、围绕童话展开或基于经典童话改编。' },
  'Henshin': { zh: '变身', descEn: 'Prominently features character or costume transformations which often grant special abilities.', descZh: '突出出现通常赋予特殊能力的角色或服装变身。' },
  'Isekai': { zh: '异世界', descEn: 'Features a character from a modern-day setting being transported into an alternate world and has to adapt to their new surroundings.', descZh: '包含现代背景的角色被传送到异世界并必须适应新环境。' },
  'Kaiju': { zh: '怪兽', descEn: 'Prominently features giant monsters.', descZh: '突出出现巨型怪兽。' },
  'Magic': { zh: '魔法', descEn: 'Prominently features magical elements or the use of magic.', descZh: '突出出现魔法元素或魔法的使用。' },
  'Mythology': { zh: '神话', descEn: 'Prominently features mythological elements, especially those from religious or cultural tradition.', descZh: '突出出现神话元素，尤其是宗教或文化传统中的神话。' },
  'Necromancy': { zh: '死灵术', descEn: 'When the dead are summoned as spirits, skeletons, or the undead, usually for the purpose of gaining information or to be used as a weapon.', descZh: '将死者以灵魂、骷髅或亡灵形式召唤，通常为获取情报或用作武器。' },
  'Reverse Isekai': { zh: '逆异世界', descEn: 'Features a character from a fantasy world who is transported into a modern-day setting.', descZh: '包含奇幻世界的角色被传送到现代背景。' },
  'Shapeshifting': { zh: '变形', descEn: 'Features character(s) who changes one\'s appearance or form.', descZh: '包含改变外貌或形态的角色。' },
  'Steampunk': { zh: '蒸汽朋克', descEn: 'Prominently features technology and designs inspired by 19th-century industrial steam-powered machinery.', descZh: '突出出现受19世纪工业蒸汽机械启发的技术与设计。' },
  'Super Power': { zh: '超能力', descEn: 'Prominently features characters with special abilities that allow them to do what would normally be physically or logically impossible.', descZh: '突出出现拥有特殊能力、能做出通常物理或逻辑上不可能之事的角色。' },
  'Superhero': { zh: '超级英雄', descEn: 'Prominently features super-powered humans who aim to serve the greater good.', descZh: '突出出现以造福大众为目标的超能力人类。' },
  'Wuxia': { zh: '武侠', descEn: 'Chinese fiction concerning the adventures of martial artists in Ancient China.', descZh: '关于古代中国武侠冒险的中国虚构作品。' },
  'Youkai': { zh: '妖怪', descEn: 'Prominently features supernatural creatures from Japanese folklore.', descZh: '突出出现日本民间传说中的超自然生物。' },
  // ── Cast-Main Cast ──
  'Anti-Hero': { zh: '反英雄', descEn: 'Features a protagonist who lacks conventional heroic attributes and may be considered a borderline villain.', descZh: '包含缺乏传统英雄特质、可能被视为准反派的主角。' },
  'Elderly Protagonist': { zh: '老年主角', descEn: 'The protagonist is either over 60 years of age, has an elderly appearance, or, in the case of non-humans, is considered elderly for their species.', descZh: '主角超过60岁、外貌苍老，或（对非人类而言）在其物种中算高龄。' },
  'Ensemble Cast': { zh: '群像剧', descEn: 'Features a large cast of characters with (almost) equal screen time and importance to the plot.', descZh: '包含大量（几乎）均等出场时间与剧情重要性的角色阵容。' },
  'Estranged Family': { zh: '疏离家庭', descEn: 'At least one family member of the MC intentionally distances themselves or a family distances themselves from a person related to the MC.', descZh: '主角至少有一名家人主动疏远，或家人疏远与主角相关的人。' },
  'Female Protagonist': { zh: '女性主角', descEn: 'Main character is female.', descZh: '主角为女性。' },
  'Male Protagonist': { zh: '男性主角', descEn: 'Main character is male.', descZh: '主角为男性。' },
  'Primarily Adult Cast': { zh: '成年主角', descEn: 'Main cast is mostly composed of characters above a high school age.', descZh: '主要阵容大多为高中以上年龄的角色。' },
  'Primarily Animal Cast': { zh: '动物主角', descEn: 'Main cast is mostly composed animal or animal-like characters.', descZh: '主要阵容大多是动物或类动物角色。' },
  'Primarily Child Cast': { zh: '儿童主角', descEn: 'Main cast is mostly composed of characters below a high school age.', descZh: '主要阵容大多是高中以下年龄的角色。' },
  'Primarily Female Cast': { zh: '女性为主', descEn: 'Main cast is mostly composed of female characters.', descZh: '主要阵容大多是女性角色。' },
  'Primarily Male Cast': { zh: '男性为主', descEn: 'Main cast is mostly composed of male characters.', descZh: '主要阵容大多是男性角色。' },
  'Primarily Teen Cast': { zh: '青少年主角', descEn: 'Main cast is mostly composed of teen characters.', descZh: '主要阵容大多是青少年角色。' },
  // ── Theme-Action ──
  'Archery': { zh: '射箭', descEn: 'Centers around the sport of archery, or prominently features the use of archery in combat.', descZh: '围绕射箭运动展开，或突出出现战斗中射箭的运用。' },
  'Battle Royale': { zh: '大逃杀', descEn: 'Centers around a fierce group competition, often violent and with only one winner.', descZh: '围绕激烈的群体竞争展开，往往暴力且只有一个胜者。' },
  'Espionage': { zh: '间谍', descEn: 'Prominently features characters infiltrating an organization in order to steal sensitive information.', descZh: '突出出现潜入组织窃取机密信息的角色。' },
  'Fugitive': { zh: '逃亡者', descEn: 'Prominently features a character evading capture by an individual or organization.', descZh: '突出出现躲避个人或组织追捕的角色。' },
  'Guns': { zh: '枪械', descEn: 'Prominently features the use of guns in combat.', descZh: '突出出现战斗中枪械的使用。' },
  'Martial Arts': { zh: '武术', descEn: 'Centers around the use of traditional hand-to-hand combat.', descZh: '围绕传统徒手格斗的运用展开。' },
  'Spearplay': { zh: '枪术', descEn: 'Prominently features the use of spears in combat.', descZh: '突出出现战斗中长枪的使用。' },
  'Swordplay': { zh: '剑术', descEn: 'Prominently features the use of swords in combat.', descZh: '突出出现战斗中剑术的运用。' },
  // ── Theme-Other-Organisations ──
  'Assassins': { zh: '刺客', descEn: 'Centers around characters who murder people as a profession.', descZh: '围绕以杀人为职业的角色展开。' },
  'Criminal Organization': { zh: '犯罪组织', descEn: 'Prominently features a group of people who commit crimes for illicit or violent purposes.', descZh: '突出出现为非法或暴力目的犯罪的群体。' },
  'Cult': { zh: '邪教', descEn: 'Features a social group with unorthodox religious, spiritual, or philosophical beliefs and practices.', descZh: '包含拥有非正统宗教、精神或哲学信仰与实践的社会群体。' },
  'Firefighters': { zh: '消防员', descEn: 'Centered around the life and activities of rescuers specialised in firefighting.', descZh: '围绕专门从事救火的救援人员的生活与活动展开。' },
  'Gangs': { zh: '帮派', descEn: 'Centers around gang organizations.', descZh: '围绕帮派组织展开。' },
  'Mafia': { zh: '黑手党', descEn: 'Centered around Italian organised crime syndicates.', descZh: '围绕意大利有组织犯罪集团展开。' },
  'Military': { zh: '军队', descEn: 'Centered around the life and activities of military personnel.', descZh: '围绕军人的生活与活动展开。' },
  'Police': { zh: '警察', descEn: 'Centers around the life and activities of law enforcement officers.', descZh: '围绕执法人员的生活与活动展开。' },
  'Triads': { zh: '三合会', descEn: 'Centered around Chinese organised crime syndicates.', descZh: '围绕华人三合会有组织犯罪集团展开。' },
  'Yakuza': { zh: '黑道', descEn: 'Centered around Japanese organised crime syndicates.', descZh: '围绕日本有组织犯罪集团（黑道）展开。' },
  // ── Theme-Other-Vehicle ──
  'Aviation': { zh: '航空', descEn: 'Regarding the flying or operation of aircraft.', descZh: '关于飞机的飞行或驾驶。' },
  'Cars': { zh: '汽车', descEn: 'Centers around the use of automotive vehicles.', descZh: '围绕机动车的使用展开。' },
  'Mopeds': { zh: '轻便摩托', descEn: 'Prominently features mopeds.', descZh: '突出出现轻便摩托车。' },
  'Motorcycles': { zh: '摩托车', descEn: 'Prominently features the use of motorcycles.', descZh: '突出出现摩托车的使用。' },
  'Ships': { zh: '舰船', descEn: 'Prominently features the use of sea-based transportation vessels.', descZh: '突出出现海上运输船只的使用。' },
  'Tanks': { zh: '坦克', descEn: 'Prominently features the use of tanks or other armoured vehicles.', descZh: '突出出现坦克或其他装甲车的使用。' },
  'Trains': { zh: '火车', descEn: 'Prominently features trains.', descZh: '突出出现火车。' },
  // ── Theme-Arts-Music ──
  'Band': { zh: '乐队', descEn: 'Main cast is a group of musicians.', descZh: '主要阵容是一群音乐家。' },
  'Classical Music': { zh: '古典音乐', descEn: 'Centers on the musical style of classical, not to be applied to anime that use classical in its soundtrack.', descZh: '围绕古典音乐风格展开，不适用于仅在配乐中使用古典乐的作品。' },
  'Dancing': { zh: '舞蹈', descEn: 'Centers around the art of dance.', descZh: '围绕舞蹈艺术展开。' },
  'Hip-hop Music': { zh: '嘻哈音乐', descEn: 'Centers on the musical style of hip-hop, not to be applied to anime that use hip-hop in its soundtrack.', descZh: '围绕嘻哈音乐风格展开，不适用于仅在配乐中使用嘻哈的作品。' },
  'Jazz Music': { zh: '爵士乐', descEn: 'Centers on the musical style of jazz, not to be applied to anime that use jazz in its soundtrack.', descZh: '围绕爵士乐风格展开，不适用于仅在配乐中使用爵士的作品。' },
  'Metal Music': { zh: '金属乐', descEn: 'Centers on the musical style of metal, not to be applied to anime that use metal in its soundtrack.', descZh: '围绕金属乐风格展开，不适用于仅在配乐中使用金属的作品。' },
  'Musical Theater': { zh: '音乐剧', descEn: 'Features a performance that combines songs, spoken dialogue, acting, and dance.', descZh: '包含结合歌曲、对白、表演与舞蹈的演出。' },
  'Rock Music': { zh: '摇滚乐', descEn: 'Centers on the musical style of rock, not to be applied to anime that use rock in its soundtrack.', descZh: '围绕摇滚乐风格展开，不适用于仅在配乐中使用摇滚的作品。' },
  // ── Setting-Scene ──
  'Bar': { zh: '酒吧', descEn: 'Partly or completely set in a bar.', descZh: '部分或完全设定在酒吧。' },
  'Boarding School': { zh: '寄宿学校', descEn: 'Features characters attending a boarding school.', descZh: '包含就读寄宿学校的角色。' },
  'Camping': { zh: '露营', descEn: 'Features the recreational activity of camping, either in a tent, vehicle, or simply sleeping outdoors.', descZh: '包含露营这一休闲活动，无论是在帐篷、车里还是直接睡在户外。' },
  'Circus': { zh: '马戏团', descEn: 'Prominently features a circus.', descZh: '突出出现马戏团。' },
  'Coastal': { zh: '沿海', descEn: 'Story prominently takes place near the beach or around a coastal area/town. Setting is near the ocean.', descZh: '故事突出发生在海滩附近或沿海地区、城镇，设定靠近海洋。' },
  'College': { zh: '大学', descEn: 'Partly or completely set in a college or university.', descZh: '部分或完全设定在大学。' },
  'Desert': { zh: '沙漠', descEn: 'Prominently features a desert environment.', descZh: '突出出现沙漠环境。' },
  'Dungeon': { zh: '地下城', descEn: 'Prominently features a dungeon environment.', descZh: '突出出现地下城环境。' },
  'Foreign': { zh: '异国', descEn: 'Partly or completely set in a country outside the country of origin.', descZh: '部分或完全设定在制作国之外的国家。' },
  'Inn': { zh: '旅馆', descEn: 'Partially or completely set in an Inn or Hotel.', descZh: '部分或完全设定在旅馆或酒店。' },
  'Konbini': { zh: '便利店', descEn: 'Predominantly features a convenience store.', descZh: '主要以便利店为背景。' },
  'Natural Disaster': { zh: '自然灾害', descEn: 'It focuses on catastrophic events of natural origin, such as earthquakes, tsunamis,  volcanic eruptions, and severe storms. These works often present situations of extreme danger in which the characters struggle to survive and overcome the adversity.', descZh: '聚焦地震、海啸、火山喷发、强风暴等自然灾害事件，这类作品常呈现角色在极端危险中挣扎求生、克服困境的场景。' },
  'Office': { zh: '办公室', descEn: 'Features people who work in a business office.', descZh: '包含在商务办公室工作的人。' },
  'Outdoor Activities': { zh: '户外活动', descEn: 'Centers around hiking, camping or other outdoor activities.', descZh: '围绕徒步、露营等户外活动展开。' },
  'Prison': { zh: '监狱', descEn: 'Partly or completely set in a prison.', descZh: '部分或完全设定在监狱。' },
  'Restaurant': { zh: '餐厅', descEn: 'Features a business that prepares and serves food and drinks to customers. Also encompasses cafes and bistros.', descZh: '包含向顾客提供食物和饮料的餐饮场所，也涵盖咖啡馆与小餐馆。' },
  'Rural': { zh: '乡村', descEn: 'Partly or completely set in the countryside.', descZh: '部分或完全设定在乡村。' },
  'School': { zh: '学校', descEn: 'Partly or completely set in a primary or secondary educational institution.', descZh: '部分或完全设定在小学或中学。' },
  'School Club': { zh: '社团', descEn: 'Partly or completely set in a school club scene.', descZh: '部分或完全设定在社团场景中。' },
  'Snowscape': { zh: '雪景', descEn: 'Prominently or partially set in a snowy environment.', descZh: '突出或部分设定在雪地环境。' },
  'Urban': { zh: '都市', descEn: 'Partly or completely set in a city.', descZh: '部分或完全设定在城市。' },
  'Wilderness': { zh: '荒野', descEn: 'Predominantly features a location with little to no human activity, such as a deserted island, a jungle, or a snowy mountain range.', descZh: '主要以几乎无人活动的地区为背景，如荒岛、丛林或雪山山脉。' },
  'Work': { zh: '职场', descEn: 'Centers around the activities of a certain occupation.', descZh: '围绕某一职业的活动展开。' },
  // ── Theme-Game ──
  'Board Game': { zh: '桌游', descEn: 'Centers around characters playing board games.', descZh: '围绕角色玩桌游展开。' },
  'E-Sports': { zh: '电竞', descEn: 'Prominently features professional video game competitions, tournaments, players, etc.', descZh: '突出出现职业电子游戏比赛、锦标赛、选手等。' },
  'Video Games': { zh: '电子游戏', descEn: 'Centers around characters playing video games.', descZh: '围绕角色玩电子游戏展开。' },
  // ── Theme-Drama ──
  'Bullying': { zh: '霸凌', descEn: 'Prominently features the use of force for intimidation, often in a school setting.', descZh: '突出出现以恐吓为目的的暴力使用，常见于校园环境。' },
  'Class Struggle': { zh: '阶级斗争', descEn: 'Contains conflict born between the different social classes. Generally between an dominant elite and a suffering oppressed group.', descZh: '包含不同社会阶级之间的冲突，通常是占统治地位的精英与受压迫的群体之间。' },
  'Coming of Age': { zh: '成长', descEn: 'Centers around a character\'s transition from childhood to adulthood.', descZh: '围绕角色从童年向成年的过渡展开。' },
  'Conspiracy': { zh: '阴谋', descEn: 'Contains one or more factions controlling or attempting to control the world from the shadows.', descZh: '包含一个或多个派系在暗处控制或试图控制世界。' },
  'Eco-Horror': { zh: '生态恐怖', descEn: 'Utilizes a horrifying depiction of ecology to explore man and its relationship with nature.', descZh: '通过恐怖的生态描绘来探讨人与自然的关系。' },
  'Fake Relationship': { zh: '假恋爱', descEn: 'When two characters enter a fake relationship that mutually benefits one or both involved.', descZh: '两个角色为了双方或一方互惠而进入假恋爱关系。' },
  'Kingdom Management': { zh: '王国经营', descEn: 'Characters in these series take on the responsibility of running a town or kingdom, whether they take control of an existing one, or build their own from the ground up.', descZh: '这类系列中的角色承担经营城镇或王国的责任，无论是接管现有王国还是从零开始建立。' },
  'Rehabilitation': { zh: '康复', descEn: 'Prominently features the recovery of a character who became incapable of social life or work.', descZh: '突出出现失去社会生活或工作能力的角色的康复过程。' },
  'Revenge': { zh: '复仇', descEn: 'Prominently features a character who aims to exact punishment in a resentful or vindictive manner.', descZh: '突出出现以怨恨或报复心态实施惩罚的角色。' },
  'Suicide': { zh: '自杀', descEn: 'The act or an instance of taking or attempting to take one\'s own life voluntarily and intentionally.', descZh: '自愿且有意图地采取或尝试结束自己生命的行为。' },
  'Tragedy': { zh: '悲剧', descEn: 'Centers around tragic events and unhappy endings.', descZh: '围绕悲剧事件与不幸结局展开。' },
  // ── Theme-Game-Card & Board Game ──
  'Card Battle': { zh: '卡牌对战', descEn: 'Centers around individuals competing in card games.', descZh: '围绕个人进行卡牌对战展开。' },
  'Go': { zh: '围棋', descEn: 'Centered around the game of Go.', descZh: '围绕围棋游戏展开。' },
  'Karuta': { zh: '歌牌', descEn: 'Centers around the game of karuta.', descZh: '围绕歌牌游戏展开。' },
  'Mahjong': { zh: '麻将', descEn: 'Centered around the game of mahjong.', descZh: '围绕麻将游戏展开。' },
  'Poker': { zh: '扑克', descEn: 'Centers around the game of poker or its variations.', descZh: '围绕扑克游戏或其变体展开。' },
  'Shogi': { zh: '将棋', descEn: 'Centers around the game of shogi.', descZh: '围绕将棋游戏展开。' },
  // ── Theme-Sci-Fi ──
  'Cyberpunk': { zh: '赛博朋克', descEn: 'Set in a future of advanced technological and scientific achievements that have resulted in social disorder.', descZh: '设定在科技高度发达却导致社会失序的未来。' },
  'Space Opera': { zh: '太空歌剧', descEn: 'Centers around space warfare, advanced technology, chivalric romance and adventure.', descZh: '围绕太空战争、先进科技、骑士式浪漫与冒险展开。' },
  'Time Loop': { zh: '时间循环', descEn: 'A character is stuck in a repetitive cycle that they are attempting to break out of. This is distinct from a manipulating time of their own choice.', descZh: '角色困在试图打破的重复循环中，这与自主操控时间不同。' },
  'Time Manipulation': { zh: '时间操控', descEn: 'Prominently features time-traveling or other time-warping phenomena.', descZh: '突出出现时间旅行或其他扭曲时间的现象。' },
  'Tokusatsu': { zh: '特摄', descEn: 'Prominently features elements that resemble special effects in Japanese live-action shows', descZh: '突出出现类似日本真人特摄剧特效的元素。' },
  // ── Demographic ──
  'Josei': { zh: '女性向', descEn: 'Target demographic is adult females.', descZh: '目标受众为成年女性。' },
  'Kids': { zh: '子供向', descEn: 'Target demographic is young children.', descZh: '目标受众为幼年儿童。' },
  'Seinen': { zh: '青年向', descEn: 'Target demographic is adult males.', descZh: '目标受众为成年男性。' },
  'Shoujo': { zh: '少女向', descEn: 'Target demographic is teenage and young adult females.', descZh: '目标受众为青少年及年轻成年女性。' },
  'Shounen': { zh: '少年向', descEn: 'Target demographic is teenage and young adult males.', descZh: '目标受众为青少年及年轻成年男性。' },
  // ── Theme-Comedy ──
  'Parody': { zh: '恶搞', descEn: 'Features deliberate exaggeration of popular tropes or a particular genre to comedic effect.', descZh: '包含为达到喜剧效果而刻意夸张流行套路或特定类型。' },
  'Satire': { zh: '讽刺', descEn: 'Prominently features the use of comedy or ridicule to expose and criticise social phenomena.', descZh: '突出出现用喜剧或嘲讽揭露与批判社会现象。' },
  'Slapstick': { zh: '闹剧', descEn: 'Prominently features comedy based on deliberately clumsy actions or embarrassing events.', descZh: '突出出现基于刻意笨拙动作或尴尬事件的喜剧。' },
  'Surreal Comedy': { zh: '超现实喜剧', descEn: 'Prominently features comedic moments that defy casual reasoning, resulting in illogical events.', descZh: '突出出现违背常理、导致不合逻辑事件的喜剧桥段。' },
  // ── Theme-Sci-Fi-Mecha ──
  'Real Robot': { zh: '真实系机器人', descEn: 'Prominently features mechanical designs loosely influenced by real-world robotics.', descZh: '突出出现受现实机器人技术松散影响的机械设计。' },
  'Super Robot': { zh: '超级系机器人', descEn: 'Prominently features large robots often piloted by hot-blooded protagonists.', descZh: '突出出现通常由热血主角驾驶的大型机器人。' },
};
// 词库总数：425
